# 3.1 Tenosr
## 基本Tensor操作

In [1]:
import torch as t

In [2]:
a=t.Tensor(2,3)   # 指定形状Tensor
b=t.Tensor([[1,2,3],[4,5,6]])   # list→Tensor
c=b.tolist()    #Tensor→list
print(a)
print(b)
print(c)

tensor([[ 2.8227e-30,  1.9250e-37,  1.0768e-35],
        [-1.1538e-29, -8.7251e-04,  9.3731e-39]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])
[[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]]


In [3]:
b_size=b.size()
print(b_size)   #Tensor.size()返回Torch.size()对象
print(b.shape)  #tensor.shape可以直接达到和tensor.size()相同的效果，但它不是方法，不用加括号
print(b.numel())
print(b.nelement())   #numel() 和nelement()作用相同

torch.Size([2, 3])
torch.Size([2, 3])
6
6


In [4]:
c=t.Tensor(b_size)   #既然b_size为 Torch.size()对象，则可以用做确定Tensor大小的参数
d=t.Tensor((2,3))    #注意和a=t.Tensor(2,3)区别
print(c)
print(d)

tensor([[ 1.0768e-35, -3.4871e-06, -1.7712e+28],
        [ 9.3731e-39,  5.2180e-38,  1.9249e-37]])
tensor([2., 3.])


## 其他创建Tensor的方法

In [5]:
print(t.ones(2,3))
print(t.zeros(2,3))
print(t.arange(1,8,2))   #从1到8，每次步长为2
print(t.linspace(1,10,3))#1到10，分为3部分
print(t.randn(2,3))  #标准正态分布
print(t.rand(2,3))   #均匀分布
print(t.randperm(5))  #长度为5的随机排列
print(t.eye(2,3))  #对角线为1，不要求行列一致

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([1, 3, 5, 7])
tensor([ 1.0000,  5.5000, 10.0000])
tensor([[ 0.6726,  0.9863,  0.1588],
        [ 1.1156,  0.6533, -0.1911]])
tensor([[0.3090, 0.9330, 0.2625],
        [0.7111, 0.0111, 0.1755]])
tensor([4, 0, 2, 1, 3])
tensor([[1., 0., 0.],
        [0., 1., 0.]])


## 常用Tensor操作
通过tensor.view()方法可以调整tensor的形状，比如将1行6列的数据调整为2行三列，但view操作不会改变计算机存储数据的方式，只是输出时的读取方式不同，view之后的新tensor与原tensor共享统一内存

In [6]:
a=t.arange(0,6)
print(a)
a=a.view(2,3)
print(a)
b=a.view(-1,3)  #-1表示按另一维度自动计算大小
print(b)

tensor([0, 1, 2, 3, 4, 5])
tensor([[0, 1, 2],
        [3, 4, 5]])
tensor([[0, 1, 2],
        [3, 4, 5]])


unsqueeze()和squeeze()用于改变数据的维度

In [7]:
print(b.unsqueeze(0))    #维度为1*2*3
print('\n',b.unsqueeze(1))    #维度为2*1*3
print('\n',b.unsqueeze(2))    #维度为2*3*1

tensor([[[0, 1, 2],
         [3, 4, 5]]])

 tensor([[[0, 1, 2]],

        [[3, 4, 5]]])

 tensor([[[0],
         [1],
         [2]],

        [[3],
         [4],
         [5]]])


In [8]:
c=b.view(1,1,1,2,3)
print(c)

tensor([[[[[0, 1, 2],
           [3, 4, 5]]]]])


In [9]:
print(c.squeeze(0))  #压缩0维
d=c
for i in range(100):  #维度大于1的就无法压缩了
    d=d.squeeze(0)
print(d)
print(c.squeeze()) #将所有维度为1的压缩

tensor([[[[0, 1, 2],
          [3, 4, 5]]]])
tensor([[0, 1, 2],
        [3, 4, 5]])
tensor([[0, 1, 2],
        [3, 4, 5]])


resize()是另一种用来调整size的方法,但它可以修改tensor的尺寸(不同于view)，即可以自动分配内存空间
**从存储的角度讲，对tensor的操作可以分为两类：**
- 不会修改自身数据，如a.add(b)，加法的结果返回一个新的tensor
- 会修改自身数据，a.add_(b)，加法的结果仍存储在a中
因为resize是会修改自身数据的，所以它的形式为：b.resize_()

In [10]:
print(b)
print(b.resize_(1,3))
print(b) #此时b已经改变

tensor([[0, 1, 2],
        [3, 4, 5]])
tensor([[0, 1, 2]])
tensor([[0, 1, 2]])


In [11]:
print(b.resize_(3,3))  #如果没有其他操作覆盖这一块区域，原来的数据是会保留的，但多出来的数据会分配存储空间

tensor([[                  0,                   1,                   2],
        [                  3,                   4,                   5],
        [8033049682695424637, 7023439528312271989, 2308669004906786925]])


## 索引操作

In [12]:
a=t.randn(3,4)
print(a)
print(a.shape)
print(a[0])  #第一个维度(数为3)选取0，第二个维度(数为4)选取全部
print(a[0,:])#同上
print(a[:,0])

tensor([[-0.4325, -0.9110,  1.6723,  0.4172],
        [-1.1078, -0.7501, -0.4187, -1.6028],
        [-0.9100,  1.1734, -1.8369, -1.1034]])
torch.Size([3, 4])
tensor([-0.4325, -0.9110,  1.6723,  0.4172])
tensor([-0.4325, -0.9110,  1.6723,  0.4172])
tensor([-0.4325, -1.1078, -0.9100])


In [13]:
print(a[:2])  #前两行
print(a[:2,0:2]) #前两行，前两列

tensor([[-0.4325, -0.9110,  1.6723,  0.4172],
        [-1.1078, -0.7501, -0.4187, -1.6028]])
tensor([[-0.4325, -0.9110],
        [-1.1078, -0.7501]])


In [14]:
a > 1 

tensor([[False, False,  True, False],
        [False, False, False, False],
        [False,  True, False, False]])

In [15]:
b=a[a>1] #挑选出所有大于1的，等价于a.masked_select(a>1)
print(b)
print(a.masked_select(a>1))

tensor([1.6723, 1.1734])
tensor([1.6723, 1.1734])


In [16]:
a[t.LongTensor([0,1])] #第0行和第1行

tensor([[-0.4325, -0.9110,  1.6723,  0.4172],
        [-1.1078, -0.7501, -0.4187, -1.6028]])

**其他常用选择函数**
 
 |函数|功能|
 |-----|----|
 |index_select(input,dim,index)|在指定dim上选取某些行和列|
 |masked_select(input,mask)|同a[a>0]，使用ByteTensor选取|
 |non_zero(input)|非零元素的下标|
 |gather(input,dim,index)|根据index，在dim维度上选取数据，输出的size与index一样|
    
**gather()的具体示例如下：**
1. 取对角线元素

In [17]:
index=t.LongTensor([[0,1,2,3]])
print(index,'\n') #第一个维度的数为1
a=t.arange(0,16).view(4,4)
print(a,'\n')
print(a.gather(0,index))
'''
0表示对第一个维度操作，然后按index的顺序依次取
即按行操作：第一行，第二行，第三行。。。，每一行按照index的顺序取
'''
index=t.LongTensor([[0,1,2,3]]).t()
print(index,'\n') #第二个维度的数为1 ，即4*1
print(a.gather(1,index)) # 在第二个维度选取数据，依次取0号，1号，2,号。。。

tensor([[0, 1, 2, 3]]) 

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]]) 

tensor([[ 0,  5, 10, 15]])
tensor([[0],
        [1],
        [2],
        [3]]) 

tensor([[ 0],
        [ 5],
        [10],
        [15]])


2. 取反对角线元素

In [18]:
index=t.LongTensor([[3,2,1,0]])
# print(index,'\n') #第二个维度的数为1 ，即4*1
print(a.gather(0,index))
index=index.t()
print(a.gather(1,index))

tensor([[12,  9,  6,  3]])
tensor([[ 3],
        [ 6],
        [ 9],
        [12]])


3. 取两个对角线上元素

In [19]:
index=t.LongTensor([[0,1,2,3],[3,2,1,0]])
print(a.gather(0,index))
index=index.t()
b=a.gather(1,index)
print(b)

tensor([[ 0,  5, 10, 15],
        [12,  9,  6,  3]])
tensor([[ 0,  3],
        [ 5,  6],
        [10,  9],
        [15, 12]])


与gather相应的逆操作是scatter_，sactter_把取出来的数据再放回去，<front color=red>注意scatter_是inplace操作</front>

In [20]:
c=t.zeros(4,4)
c.scatter_(1,index,b.float())

tensor([[ 0.,  0.,  0.,  3.],
        [ 0.,  5.,  6.,  0.],
        [ 0.,  9., 10.,  0.],
        [12.,  0.,  0., 15.]])

上面这行代码如果按照原书中的写法会报错，报错如下：

\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-

RuntimeError&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;Traceback (most recent call last)

< ipython-input-26-8c806181a3e0 > in < module >

&emsp;&emsp;&emsp;1 c=t.zeros(4,4)

\-\-\-\-\-> 2 c.scatter_(1,index,b)

RuntimeError: Expected object of scalar type Float but got scalar type Long for argument #4 'src' in call to _th_scatter_

## 高级索引
略
## Tensor类型
默认的tensor为FloatTensor，可以通过t.set_default_tensor_type修改默认类型
各种类型之间可以相互转换，type(new_type)是通用的做法
CPU tensor和GPU tensor之间的互相转换通过tensor.cuda和tensor.cpu实现
同时Tensor还有一个new方法，用法与t.Tensor()一样

In [27]:
t.set_default_tensor_type('torch.DoubleTensor')
a=t.Tensor(2,3)
print(a)
b=a.float()
print(b)
c=a.type_as(b)
print(c)
t.set_default_tensor_type('torch.FloatTensor')  #还原为默认

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float32)
tensor([[0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float32)


随着版本更新，原书代码会报错：
TypeError: only floating-point types are supported as the default type
因为Int型现在不支持设置为default，只能设置float类型的值为默认类型(float，double和half)

## 逐元素操作
这部分操作会对tensor的每一个元素进行操作

![](https://s2.ax1x.com/2020/01/29/1QAD0A.png)

In [31]:
a=t.arange(0,6).view(2,3)
print(a,'\n')
print(t.clamp(a,min=3))

tensor([[0, 1, 2],
        [3, 4, 5]]) 

tensor([[3, 3, 3],
        [3, 4, 5]])


## 归并操作
![](https://s2.ax1x.com/2020/01/29/1QEJBj.png)
以上函数大多都有参数dim，用来指定在哪一个维度上进行操作
假设输入的形状为(m,n,k):
- dim=0，输出形状(1,n,k)或(n,k)
- dim=1，输出形状(m,1,k)或(m,k)
- dim=2，输出形状(m,n,1)或(m,n)

size中是否具有1，取决于参数keepdim，keepdim=True就会保留维度1（pytorch 0.2.0 起keepdim默认为False）

In [39]:
b=t.ones(2,3)
print(b.sum(dim=0,keepdim=True))
print(b.sum(0)) #注意区别
print(b.sum(dim=1))

tensor([[2., 2., 2.]])
tensor([2., 2., 2.])
tensor([3., 3.])
