# 3.1 Tenosr
## 基本Tensor操作

In [1]:
import torch as t

In [2]:
a=t.Tensor(2,3)   # 指定形状Tensor
b=t.Tensor([[1,2,3],[4,5,6]])   # list→Tensor
c=b.tolist()    #Tensor→list
print(a)
print(b)
print(c)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])
[[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]]


In [3]:
b_size=b.size()
print(b_size)   #Tensor.size()返回Torch.size()对象
print(b.shape)  #tensor.shape可以直接达到和tensor.size()相同的效果，但它不是方法，不用加括号
print(b.numel())
print(b.nelement())   #numel() 和nelement()作用相同

torch.Size([2, 3])
torch.Size([2, 3])
6
6


In [4]:
c=t.Tensor(b_size)   #既然b_size为 Torch.size()对象，则可以用做确定Tensor大小的参数
d=t.Tensor((2,3))    #注意和a=t.Tensor(2,3)区别
print(c)
print(d)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([2., 3.])


## 其他创建Tensor的方法

In [5]:
print(t.ones(2,3))
print(t.zeros(2,3))
print(t.arange(1,8,2))   #从1到8，每次步长为2
print(t.linspace(1,10,3))#1到10，分为3部分
print(t.randn(2,3))  #标准正态分布
print(t.rand(2,3))   #均匀分布
print(t.randperm(5))  #长度为5的随机排列
print(t.eye(2,3))  #对角线为1，不要求行列一致

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([1, 3, 5, 7])
tensor([ 1.0000,  5.5000, 10.0000])
tensor([[-1.0081,  0.5772,  0.3315],
        [-0.7035,  1.0028, -0.3037]])
tensor([[0.4117, 0.1650, 0.1305],
        [0.6868, 0.0379, 0.0322]])
tensor([0, 2, 3, 1, 4])
tensor([[1., 0., 0.],
        [0., 1., 0.]])


## 常用Tensor操作
通过tensor.view()方法可以调整tensor的形状，比如将1行6列的数据调整为2行三列，但view操作不会改变计算机存储数据的方式，只是输出时的读取方式不同，view之后的新tensor与原tensor共享统一内存

In [6]:
a=t.arange(0,6)
print(a)
a=a.view(2,3)
print(a)
b=a.view(-1,3)  #-1表示按另一维度自动计算大小
print(b)

tensor([0, 1, 2, 3, 4, 5])
tensor([[0, 1, 2],
        [3, 4, 5]])
tensor([[0, 1, 2],
        [3, 4, 5]])


unsqueeze()和squeeze()用于改变数据的维度

In [7]:
print(b.unsqueeze(0))    #维度为1*2*3
print('\n',b.unsqueeze(1))    #维度为2*1*3
print('\n',b.unsqueeze(2))    #维度为2*3*1

tensor([[[0, 1, 2],
         [3, 4, 5]]])

 tensor([[[0, 1, 2]],

        [[3, 4, 5]]])

 tensor([[[0],
         [1],
         [2]],

        [[3],
         [4],
         [5]]])


In [8]:
c=b.view(1,1,1,2,3)
print(c)

tensor([[[[[0, 1, 2],
           [3, 4, 5]]]]])


In [9]:
print(c.squeeze(0))  #压缩0维
d=c
for i in range(100):  #维度大于1的就无法压缩了
    d=d.squeeze(0)
print(d)
print(c.squeeze()) #将所有维度为1的压缩

tensor([[[[0, 1, 2],
          [3, 4, 5]]]])
tensor([[0, 1, 2],
        [3, 4, 5]])
tensor([[0, 1, 2],
        [3, 4, 5]])


resize()是另一种用来调整size的方法,但它可以修改tensor的尺寸(不同于view)，即可以自动分配内存空间
**从存储的角度讲，对tensor的操作可以分为两类：**
- 不会修改自身数据，如a.add(b)，加法的结果返回一个新的tensor
- 会修改自身数据，a.add_(b)，加法的结果仍存储在a中
因为resize是会修改自身数据的，所以它的形式为：b.resize_()

In [10]:
print(b)
print(b.resize_(1,3))
print(b) #此时b已经改变

tensor([[0, 1, 2],
        [3, 4, 5]])
tensor([[0, 1, 2]])
tensor([[0, 1, 2]])


In [11]:
print(b.resize_(3,3))  #如果没有其他操作覆盖这一块区域，原来的数据是会保留的，但多出来的数据会分配存储空间

tensor([[                0,                 1,                 2],
        [                3,                 4,                 5],
        [32651561162571873, 31525614010564703, 28992395054481520]])


## 索引操作

In [12]:
a=t.randn(3,4)
print(a)
print(a.shape)
print(a[0])  #第一个维度(数为3)选取0，第二个维度(数为4)选取全部
print(a[0,:])#同上
print(a[:,0])

tensor([[ 0.7543, -0.9249,  0.5559,  0.7851],
        [-0.7450,  0.6337, -1.2043, -0.4728],
        [ 1.0194, -0.6855,  0.2657,  0.9690]])
torch.Size([3, 4])
tensor([ 0.7543, -0.9249,  0.5559,  0.7851])
tensor([ 0.7543, -0.9249,  0.5559,  0.7851])
tensor([ 0.7543, -0.7450,  1.0194])


In [13]:
print(a[:2])  #前两行
print(a[:2,0:2]) #前两行，前两列

tensor([[ 0.7543, -0.9249,  0.5559,  0.7851],
        [-0.7450,  0.6337, -1.2043, -0.4728]])
tensor([[ 0.7543, -0.9249],
        [-0.7450,  0.6337]])


In [14]:
a > 1 

tensor([[False, False, False, False],
        [False, False, False, False],
        [ True, False, False, False]])

In [15]:
b=a[a>1] #挑选出所有大于1的，等价于a.masked_select(a>1)
print(b)
print(a.masked_select(a>1))

tensor([1.0194])
tensor([1.0194])


In [16]:
a[t.LongTensor([0,1])] #第0行和第1行

tensor([[ 0.7543, -0.9249,  0.5559,  0.7851],
        [-0.7450,  0.6337, -1.2043, -0.4728]])

In [17]:
help(t.LongTensor()) # 啊太长不看

Help on Tensor in module torch object:

class Tensor(torch._C._TensorBase)
 |  Method resolution order:
 |      Tensor
 |      torch._C._TensorBase
 |      builtins.object
 |  
 |  Methods defined here:
 |  
 |  __abs__ = abs(...)
 |      abs() -> Tensor
 |      
 |      See :func:`torch.abs`
 |  
 |  __array__(self, dtype=None)
 |  
 |  __array_wrap__(self, array)
 |      # Wrap Numpy array again in a suitable tensor when done, to support e.g.
 |      # `numpy.sin(tensor) -> tensor` or `numpy.greater(tensor, 0) -> ByteTensor`
 |  
 |  __contains__(self, element)
 |      Check if `element` is present in tensor
 |      
 |      Arguments:
 |          element (Tensor or scalar): element to be checked
 |              for presence in current tensor"
 |  
 |  __deepcopy__(self, memo)
 |  
 |  __dir__(self)
 |      __dir__() -> list
 |      default dir() implementation
 |  
 |  __eq__ = eq(...)
 |      eq(other) -> Tensor
 |      
 |      See :func:`torch.eq`
 |  
 |  __floordiv__(self, othe

**其他常用选择函数**
 
 |函数|功能|
 |-----|----|
 |index_select(input,dim,index)|在指定dim上选取某些行和列|
 |masked_select(input,mask)|同a[a>0]，使用ByteTensor选取|
 |non_zero(input)|非零元素的下标|
 |gather(input,dim,index)|根据index，在dim维度上选取数据，输出的size与index一样|
    
**gather()的具体示例如下：**
1. 取对角线元素

In [24]:
index=t.LongTensor([[0,1,2,3]])
print(index,'\n') #第一个维度的数为1
a=t.arange(0,16).view(4,4)
print(a,'\n')
print(a.gather(0,index))
'''
0表示对第一个维度操作，然后按index的顺序依次取
即按行操作：第一行，第二行，第三行。。。，每一行按照index的顺序取
'''
index=t.LongTensor([[0,1,2,3]]).t()
print(index,'\n') #第二个维度的数为1 ，即4*1
print(a.gather(1,index)) # 在第二个维度选取数据，依次取0号，1号，2,号。。。

tensor([[0, 1, 2, 3]]) 

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]]) 

tensor([[ 0,  5, 10, 15]])
tensor([[0],
        [1],
        [2],
        [3]]) 

tensor([[ 0],
        [ 5],
        [10],
        [15]])


2. 取反对角线元素

In [28]:
index=t.LongTensor([[3,2,1,0]])
# print(index,'\n') #第二个维度的数为1 ，即4*1
print(a.gather(0,index))
index=index.t()
print(a.gather(1,index))

tensor([[12,  9,  6,  3]])
tensor([[ 3],
        [ 6],
        [ 9],
        [12]])


3. 取两个对角线上元素

In [42]:
index=t.LongTensor([[0,1,2,3],[3,2,1,0]])
print(a.gather(0,index))
index=index.t()
print(a.gather(1,index))

tensor([[ 0,  5, 10, 15],
        [12,  9,  6,  3]])
tensor([[ 0,  3],
        [ 5,  6],
        [10,  9],
        [15, 12]])


与gather相应的逆操作是scatter_，sactter_把取出来的数据再放回去，<front color=red>注意scatter_是inplace操作</front>