# python中的数据类型
## Python整型
当我们在 Python 中定义一个整型，例如 x = 10000 时， x 并不是一个“原生”整型，而是一个指针，指向一个 C 语言的复合结构体，结构体里包含了一些值。

Python 3.4 中的一个整型实际上包括 4 个部分。
- ob_refcnt 是一个引用计数，它帮助 Python 默默地处理内存的分配和回收。
- ob_type 将变量的类型编码。
- ob_size 指定接下来的数据成员的大小。
- ob_digit 包含我们希望 Python 变量表示的实际整型值。

C 语言整型本质上是对应某个内存位置的标签，里面存储的字节会编码成整型。而 Python 的整型其实是一个指针，指向包含这个 Python 对象所有信息的某个内存位置，其中包括可以转换成整型的字节。由于 Python 的整型结构体里面还包含了大量额外的信息，所以 Python 可以自由、动态地编码。<font color=red>但是， Python 类型中的这些额外信息也会成为负担，在多个对象组合的结构体中尤其明显。</font>

## Python列表
## Python中的固定类型数组
Python 提供了几种将数据存储在有效的、固定类型的数据缓存中的选项。内置的数组
（array）模块（在 Python 3.3 之后可用）可以用于创建统一类型的密集数组：

In [1]:
import array
L = list(range(10))
A = array.array('i', L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

这里的 'i' 是一个数据类型码，表示数据为整型。更实用的是NumPy包中的`ndarray`对象。 Python 的数组对象提供了数组型数据的有效存储，而 NumPy 为该数据加上了高效的操作。稍后将介绍这些操作，这里先展示几种创建NumPy 数组的方法。

In [2]:
import numpy as np

## 从Python列表创建数组

In [4]:
a=np.array([1,4,2,5,3])

In [5]:
type(a)

numpy.ndarray

不同于 Python 列表， NumPy 要求数组必须包含同一类型的数据。如果类型不配， NumPy 将会向上转换（如果可行）。**这里整型被转换为浮点型：**

In [6]:
np.array([3.14,4,2,3])

array([3.14, 4.  , 2.  , 3.  ])

In [7]:
np.array([1, 2, 3, 4], dtype='float32')# 用dtype明确指定数据类型

array([1., 2., 3., 4.], dtype=float32)

不同于 Python 列表， NumPy 数组可以被指定为多维的：

In [8]:
np.array([range(i,i+3)for i in [2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

## 从头创建数组

In [9]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [10]:
np.ones((3,5),dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
np.full((3,5),3.14)
#np.full((3,5),fill_value=3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [14]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [15]:
# 创建一个5个元素的数组，这5个数均匀地分配到0~1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [16]:
np.random.random((3, 3))# 均匀分布0-1                                                                     

array([[0.60069501, 0.16124337, 0.09314837],
       [0.93724324, 0.08407901, 0.11671988],
       [0.76736868, 0.73005615, 0.54451843]])

In [17]:
# 创建一个3×3的、均值为0、方差为1的
# 正态分布的随机数数组
np.random.normal(0, 1, (3, 3))

array([[ 0.92031182, -0.6361802 ,  0.99764715],
       [-1.7742608 , -1.08289194, -2.20611947],
       [ 1.56708642,  0.83087008, -0.62993323]])

创建一个3×3的、\[0, 10)区间的随机整型数组

In [18]:
np.random.randint(0, 10, (3, 3))

array([[9, 9, 0],
       [7, 1, 0],
       [5, 2, 3]])

In [19]:
# 创建一个3×3的单位矩阵
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
# 创建一个由3个整型数组成的未初始化的数组
# 数组的值是内存空间中的任意值
np.empty(3)

array([1., 1., 1.])

## NumPy标准数据类型
NumPy 数组包含同一类型的值，因此详细了解这些数据类型及其限制是非常重要的。